### ISSUE TITLE
Please grant npm access

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.icons-smarthome#1]
@jogibear9988 

This community adapter is not yet added to iobroker-community-adapters at npm.

Please grant access at npm to me so that I can add it to the iobroker-community-adapters organization at npm.
**Please execute "npm owner add mcm1957 iobroker.icons-smarthome" at the commandline.**

Thanks in advance.
Please feel free to contact me if you have any questions.

**Comment by jogibear9988** [comment]
Why this now?

**Comment by mcm1957** [comment]
Hi,

This adapter is an adapter where the repository is owned by iobroker-community-adapters. ('community adapter'). The corresponding npm should/must be assigned to the iobroker-community-adapters orga at npm too. This is no new setup. Normally adapters are assigne the the npm organisation during movement to iobroker-community-adapters. See required steps at https://github.com/iobroker-community-adapters/info#add-git-repo-to-organization. This step is normally performed by either the person performing the migration od Apollon77 / Bluefox. 

Some adapters have missed this step in the past. I'm currently working on fixing these issues. This happens in coordination with Apollon77 and asn ais to him as he currently has nearly no spare time. So I would kindly ask to send the invite to let me continue.

In addtion I will explicitly ask @Apollon77 to confirm and to correct my explanation if its somehow misleading or something is missing. Please contact @Apollon77 yourself directly if you have any concerns.

Martin

P.S:
Perfoming the checks mentioned above I've seen that the icon adapters are still pending for latest and assigned to Apollon77. I've discussed this fact with him yesterday and I will finalize the latest repo tasks myself - most likely today - as he is out of resources to do this himself at the meoment and the adapters should no longer be pending. Sorry for the inappropiate and long delay.

**Comment by jogibear9988** [comment]
Didn't know taht we setup this npm org. Cause when I started the iobroker-community github org, I didn't create an extra npm org. Will do on monday.

**Comment by mcm1957** [comment]
No hurry - its not critical.
Sorry, that I did not explain in detail at first request. Apollon can answer any additional question for sure.

**Comment by jogibear9988** [comment]
done

**Comment by mcm1957** [comment]
@jogibear9988 
Thanks for the invite.

There have been some news from npm/github which I received yesterday evening / during the last night. There have been some changes by npm which cause problems with the current usage of iobroker-community-adapters. I'm currently (together with @Apollon) investigating the impact. Some questions regarding the futire of the npm security / access system are still unanswered.

So please do not be surprised if the adapters do not show up at the community within a few days. It looks like this is no longer possible. Sorry, that I could not inform you earlier - as I wrote I got the frist answers yesterday evening and the some additional questions are still unanswered by github/npm.

If you need more info, please contact me or @Apollon. Feel free to contact me personally at telegramm.

**Comment by jogibear9988** [comment]
if you need changes at the github org, feel free to ask me

**Comment by mcm1957** [comment]
Thanks

The problem is that since a short tome npm allows additions to an orgea ONLY by the direct npm package ower who in addition must be owner at the orga. Who the direct owner of an npm package is is only visible for npm github suppoert. And transferring the direct owner can also be done only by support team. This looks like a potential problem if package owners are no longer reachable....

We ate currently investigating what tovdonin the long term. We did not receive a statement of npm wether the changes effect only orfa addition / removalbor i.e. invites too 

So please do kot leave us without saying good bye. Or bett do not leave at all.

Thanks for soending your time and work.

I or @apollon77 will contact you if any action seems appe
Ropiate
